#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: publish python-course-site/ to GitHub Pages.
# Run this from inside the python-course-site/ folder itself, in your own
# real Terminal (not through Claude) — it needs your real GitHub credentials.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "把 Python 課程網站發佈到 GitHub Pages"

# ── Stage 1: check environment ─────────────────────────────────────────────
stage "檢查環境"
say "確認這台電腦上有 git，以及 GitHub 的官方命令列工具 gh（有的話可以自動化大部分步驟）。"

if ! command -v git >/dev/null 2>&1; then
  warn "找不到 git，這個 repo 沒辦法用命令列建立。請先安裝 git 再重跑這個 wizard。"
  exit 1
fi
note "✓ 找到 git"

HAS_GH=0
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    HAS_GH=1
    note "✓ 找到 gh，而且已經登入——之後幾個步驟可以自動幫你做。"
  else
    warn "找到 gh，但還沒登入。"
    if confirm "現在要跑 gh auth login 登入嗎？"; then
      gh auth login || true
      if gh auth status >/dev/null 2>&1; then HAS_GH=1; fi
    fi
  fi
else
  warn "沒有裝 gh（GitHub CLI）。沒關係，接下來的步驟會改成用瀏覽器手動做。"
  note "之後想要更自動化，可以到 https://cli.github.com 安裝。"
fi
pause

# ── Stage 2: create the GitHub repo ────────────────────────────────────────
stage "建立 GitHub Repository"
say "這一步只會建立一個全新、獨立的 repo，只包含這個課程網站的內容——不會動到你原本 ecgtizer-neurokit2 那個私有專案。"
ask GITHUB_USERNAME "你的 GitHub 帳號名稱："
ask REPO_NAME "這個新 repo 想取什麼名字？[Enter 用預設]"
if [[ -z "$REPO_NAME" ]]; then REPO_NAME="python-course"; fi
write_env GITHUB_USERNAME "$GITHUB_USERNAME"
write_env REPO_NAME "$REPO_NAME"

if [[ "$HAS_GH" -eq 1 ]]; then
  say "用 gh 自動建立 repo（public，因為要用 GitHub Pages 公開分享）……"
  if gh repo view "$GITHUB_USERNAME/$REPO_NAME" >/dev/null 2>&1; then
    note "repo $GITHUB_USERNAME/$REPO_NAME 已經存在了，跳過建立，直接用它。"
  else
    gh repo create "$GITHUB_USERNAME/$REPO_NAME" --public --source=. --remote=origin
  fi
  if ! git remote get-url origin >/dev/null 2>&1; then
    git remote add origin "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
  fi
  note "✓ repo 建好了，remote origin 也設定好了"
else
  open_url "https://github.com/new"
  step "Repository name 填：$REPO_NAME"
  step "選 Public（GitHub Pages 免費版只支援 public repo）"
  step "不要勾選 'Add a README file'（這個資料夾已經有內容了）"
  step "按 'Create repository'"
  pause "建好之後按 Enter 繼續"
  if git remote get-url origin >/dev/null 2>&1; then
    git remote set-url origin "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
  else
    git remote add origin "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
  fi
  note "✓ 已經把這個資料夾指向 https://github.com/$GITHUB_USERNAME/$REPO_NAME"
fi

# ── Stage 3: push ───────────────────────────────────────────────────────────
stage "推上去（git push）"
if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
  say "這個資料夾還有沒 commit 的變更（例如這個 wizard 腳本自己），先幫你 commit 起來。"
  git add -A
  git commit -q -m "Add publish wizard" || true
fi
CURRENT_BRANCH="$(git branch --show-current 2>/dev/null || echo master)"
if [[ "$CURRENT_BRANCH" != "main" ]]; then
  git branch -M main
  CURRENT_BRANCH="main"
fi
say "準備把這個資料夾目前的內容 push 到 $GITHUB_USERNAME/$REPO_NAME 的 main branch。"
if git push -u origin main 2>/tmp/push-err.log; then
  note "✓ push 成功"
else
  warn "push 失敗了，通常是因為這台電腦的 git 還沒設定好跟 GitHub 的登入方式。"
  cat /tmp/push-err.log 2>/dev/null || true
  say "最快的修法：如果你有裝 gh，跑 'gh auth setup-git' 之後再跑一次這個 wizard；"
  say "或是改用 SSH remote：git remote set-url origin git@github.com:$GITHUB_USERNAME/$REPO_NAME.git"
  SKIPPED+=("git push（手動排除登入問題後，自己跑 git push -u origin main）")
fi

# ── Stage 4: enable GitHub Pages ────────────────────────────────────────────
stage "開啟 GitHub Pages"
if [[ "$HAS_GH" -eq 1 ]]; then
  say "用 gh 自動開啟 GitHub Pages（從 main branch 的根目錄發佈）……"
  if gh api -X POST "repos/$GITHUB_USERNAME/$REPO_NAME/pages" -f "source[branch]=main" -f "source[path]=/" >/dev/null 2>&1; then
    note "✓ GitHub Pages 已經開啟"
  elif gh api -X PUT "repos/$GITHUB_USERNAME/$REPO_NAME/pages" -f "source[branch]=main" -f "source[path]=/" >/dev/null 2>&1; then
    note "✓ GitHub Pages 設定已更新"
  else
    warn "自動開啟失敗，改成手動設定："
    open_url "https://github.com/$GITHUB_USERNAME/$REPO_NAME/settings/pages"
    step "Build and deployment → Source 選 'Deploy from a branch'"
    step "Branch 選 main，資料夾選 / (root)，按 Save"
    pause "設定好之後按 Enter 繼續"
    SKIPPED+=("GitHub Pages 設定（如果上面自動設定失敗，請照上面步驟手動設定）")
  fi
else
  open_url "https://github.com/$GITHUB_USERNAME/$REPO_NAME/settings/pages"
  step "Build and deployment → Source 選 'Deploy from a branch'"
  step "Branch 選 main，資料夾選 / (root)，按 Save"
  pause "設定好之後按 Enter 繼續"
fi

# ── Stage 5: done ────────────────────────────────────────────────────────────
stage "完成"
SITE_URL="https://$GITHUB_USERNAME.github.io/$REPO_NAME/"
say "網站網址：$SITE_URL"
note "第一次啟用通常要等 1-2 分鐘才會生效，等一下如果打不開，稍等再試一次。"
if confirm "現在要打開網站看看嗎？"; then
  open_url "$SITE_URL"
fi

finish
say "之後想加新的一課：回到跟 Claude 的對話說一聲，產生好新的 HTML 檔案、更新 index.html 之後，"
say "在這個資料夾裡跑：git add -A && git commit -m '...' && git push，網站會自動更新。"
